---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.ibm.com/Ondrej-Svec2/gitops?ref=main
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: cicd
spec: {}
status: {}
