apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/ondrejsvec-ibm/cloudpak-gitops?ref=main
  creationTimestamp: null
  name: stage
spec: {}
status: {}
